# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/inventory_db

# Security Credentials for Testing
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
